# Generated by Django 5.2.8 on 2025-11-06 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
