# Generated by Django 5.2.8 on 2025-11-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application_image_alter_application_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
    ]
